In [1]:
#Phase 1
print("Hello,Iris!")

Hello,Iris!

In [20]:
#Phase 2
#load dataset


import pandas as pd

column_names = [
    'sepal_length',
    'sepal_width',
    'petal_length',
    'petal_width',
    'species'
]

# Load the Iris dataset from the folder
df = pd.read_csv(
    r'C:\Users\ERC\iris (1)\iris.data',
    header=None,
    names=column_names
)

# Show the first 5 rows
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [1]:
# 1. Variables
# Store basic metadata about the Iris dataset

n_rows = 150
n_species = 3
n_features = 4

print("Rows:", n_rows)
print("Species:", n_species)
print("Features:", n_features)

Rows: 150
Species: 3
Features: 4

In [2]:
# Control structures 
# Check petal and sepal length and label

# Control structure
petal_length = 1.7

if petal_length > 1.5:
    print("Large petal")
else:
    print("Small petal")

Large petal

In [2]:
# 3. Loop
# Print each Iris species in the dataset

species = ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]

for flower in species:
    print("Species:", flower)

Species: Iris-setosa
Species: Iris-versicolor
Species: Iris-virginica

In [3]:
# 4. Function
# Classify flower size using sepal and petal length

def classify_flower(sepal_length, petal_length):
    if sepal_length <= 0 or petal_length <= 0:
        return "Invalid Measurement"

    if sepal_length < 5.0 and petal_length < 2.0:
        return "Small"
    elif sepal_length <= 6.5 and petal_length <= 4.8:
        return "Medium"
    else:
        return "Large"


sample_measurements = [
    (4.9, 1.4),
    (6.0, 4.2),
    (6.9, 5.4)
]

for sepal, petal in sample_measurements:
    result = classify_flower(sepal, petal)
    print("Sepal:", sepal, "Petal:", petal, "Classification:", result)

Sepal: 4.9 Petal: 1.4 Classification: Small
Sepal: 6.0 Petal: 4.2 Classification: Medium
Sepal: 6.9 Petal: 5.4 Classification: Large

In [ ]:
#phase 3

In [6]:
import csv

with open("Downloads/iris/iris.data", "r") as file:
    reader = csv.reader(file)
    iris_data = list(reader)

iris_data = [row for row in iris_data if row]

print("Number of rows:", len(iris_data))

for row in iris_data[:5]:
    print(row)

Number of rows: 150
['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.0', '1.4', '0.2', 'Iris-setosa']
['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']
['4.6', '3.1', '1.5', '0.2', 'Iris-setosa']
['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']

In [7]:
# Get the number of rows
row_count = len(iris_data)

# Make lists for each measurement
sepal_length = []
sepal_width = []
petal_length = []
petal_width = []

# Add the numbers from the dataset into the lists
for row in iris_data:
    sepal_length.append(float(row[0]))
    sepal_width.append(float(row[1]))
    petal_length.append(float(row[2]))
    petal_width.append(float(row[3]))

# Print row count
print("Row count:", row_count)

# Print minimum, maximum, and average
print("Sepal Length")
print("Minimum:", min(sepal_length))
print("Maximum:", max(sepal_length))
print("Average:", sum(sepal_length) / row_count)

print()

print("Sepal Width")
print("Minimum:", min(sepal_width))
print("Maximum:", max(sepal_width))
print("Average:", sum(sepal_width) / row_count)

print()

print("Petal Length")
print("Minimum:", min(petal_length))
print("Maximum:", max(petal_length))
print("Average:", sum(petal_length) / row_count)

print()

print("Petal Width")
print("Minimum:", min(petal_width))
print("Maximum:", max(petal_width))
print("Average:", sum(petal_width) / row_count)

Row count: 150
Sepal Length
Minimum: 4.3
Maximum: 7.9
Average: 5.843333333333334

Sepal Width
Minimum: 2.0
Maximum: 4.4
Average: 3.0540000000000003

Petal Length
Minimum: 1.0
Maximum: 6.9
Average: 3.758666666666666

Petal Width
Minimum: 0.1
Maximum: 2.5
Average: 1.1986666666666668

In [8]:
# Create a new text file called summary.txt
with open("summary.txt", "w") as file:

    # Write the title
    file.write("Iris Dataset Summary\n")
    file.write("\n")

    # Write the total number of rows
    file.write("Row Count: " + str(row_count) + "\n")
    file.write("\n")

    # Sepal length summary
    file.write("Sepal Length\n")
    file.write("Minimum: " + str(min(sepal_length)) + "\n")
    file.write("Maximum: " + str(max(sepal_length)) + "\n")
    file.write("Average: " + str(round(sum(sepal_length) / row_count, 2)) + "\n")
    file.write("\n")

    # Sepal width summary
    file.write("Sepal Width\n")
    file.write("Minimum: " + str(min(sepal_width)) + "\n")
    file.write("Maximum: " + str(max(sepal_width)) + "\n")
    file.write("Average: " + str(round(sum(sepal_width) / row_count, 2)) + "\n")
    file.write("\n")

    # Petal length summary
    file.write("Petal Length\n")
    file.write("Minimum: " + str(min(petal_length)) + "\n")
    file.write("Maximum: " + str(max(petal_length)) + "\n")
    file.write("Average: " + str(round(sum(petal_length) / row_count, 2)) + "\n")
    file.write("\n")

    # Petal width summary
    file.write("Petal Width\n")
    file.write("Minimum: " + str(min(petal_width)) + "\n")
    file.write("Maximum: " + str(max(petal_width)) + "\n")
    file.write("Average: " + str(round(sum(petal_width) / row_count, 2)) + "\n")

# Let us know the file was created
print("summary.txt created successfully")

summary.txt created successfully

In [9]:
# Import pandas
import pandas as pd

# Give names to each column
column_names = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

# Read the Iris data file using pandas
df = pd.read_csv("Downloads/iris/iris.data", names=column_names)

# Show the first 5 rows
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
# Check for missing values
print(df.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
# Check the column names
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [12]:
# Check the data types
print(df.dtypes)

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [13]:
# Remove any empty rows
df = df.dropna()

# Remove duplicate rows
df = df.drop_duplicates()

# Save the cleaned dataset as a new CSV file
df.to_csv("iris_cleaned.csv", index=False)

# Show a message when finished
print("iris_cleaned.csv created successfully")

iris_cleaned.csv created successfully